### ISSUE TITLE
 0 is not a symbol error in specs

### ISSUE THREAD

**Issue by sebfie** [rebelidealist/stripe-ruby-mock#265]
Hello, 

I try to make this test work : 

```
plan = stripe_helper.create_plan(id: "myplan",amount: 100,trial_period_days: 0)
customer = Stripe::Customer.create(email: user.email)
customer.subscriptions.create(plan: plan.id)
Stripe::Customer.retrieve(customer.id).save
````

And I got the error :+1: 
```
Failure/Error: Stripe::Customer.retrieve(customer.id).save
     TypeError:
       0 is not a symbol
```

Any advice?

**Comment by alexmamonchik** [comment]
@sebfie use `customer.save` instead of `Stripe::Customer.retrieve(customer.id).save`.

**Comment by gbingersoll** [comment]
I ran into a similar issue to @sebfie but in a situation where I was updating card info.

    customer = Stripe::Customer.retrieve(self.stripe_id)
    customer.source = self.credit_card_token
    customer.save

would generate the 0 is not a symbol error.

I tracked this down, and the Stripe gem (1.30.2) is passing additional, unneeded parameters in its post request.

    params = {
      source => 'tok1234',
      subscriptions => {
        data => {
          0 => {plan=> {}, metadata => {}
      },
      sources => {data => nil}
    }

These parameters get merged with the customer response object in the `StripeMock::RequestHandlers::Customers::update_customer`. When the Stripe gem tries to deserialize this, having '0' as a key generates an error. (`sources` also later results in an undefined method `retrieve` error.)

    def update_customer(route, method_url, params, headers)
      params.delete :subscriptions
      params.delete :sources
      
      route =~ method_url
      cus = assert_existence :customer, $1, customers[$1]
      cus.merge!(params)
      ...

By removing these parameters, the errors go away, but simply deleting them may cause problems in some other situation. My app's specs are all passing again though.

**Comment by alexmamonchik** [comment]
@sebfie @gbingersoll Can you get updates for stripe-ruby-mock and check your bug again. Looks like fixed.

**Comment by gbingersoll** [comment]
After updating stripe-ruby-mock to 49b3c5e and stripe to 1.31.0, I am now getting the error:

    undefined method `retrieve' for #<Stripe::StripeObject:0x007ffa2d455450> 

I saw this previously after fixing the `0 is not a symbol` error manually. That error seemed to be only related to the `subscriptions` param, and this error was related to the `sources` param.

Something changed in the way that Stripe is serializing data in v1.31.0. I haven't investigated in detail, but I did notice that now during my test, the params come into stripe-ruby-mock `update_customer` as:

    {
      :source=>"test_tok_5",
      :sources=>{:data=>[{}]},
      :subscriptions=>{:data=>[{:plan=>{}, :metadata=>{}}]}
    }

...so the checks that remove these keys are failing, and the keys are not being removed:

    params[:sources][:data].nil? == false
    params[:subscriptions][:data].nil? == false

In the `sources` case, `:data` used to be `nil`, but now it is an array containing an empty hash.

**Comment by alexmamonchik** [comment]
@sebfie can you check again with new version of gem `2.2.1` ?

**Comment by PlugIN73** [comment]
@alexmamonchik i just updated stripe ruby mock to 2.2.2 and stripe to 1.31.0 and have this error:
undefined method `retrieve' for #<Stripe::StripeObject:0x007f1abceecb58>

**Comment by jrmyward** [comment]
FWIW, everything works as expected (at least for me) after upgrading to  `stripe-ruby-mock 2.2.2` and `stripe 1.31.0`.

**Comment by alexmamonchik** [comment]
@PlugIN73 I think you tried 2.2.1 because 2.2.2 released few days ago :-) Please, try 2.2.2 now.
