### ISSUE TITLE
`Stripe::Subscription.create` fails in version 2.5.5

### ISSUE THREAD

**Issue by cap10morgan** [rebelidealist/stripe-ruby-mock#563]
`Stripe::Subscription.create` fails in version 2.5.5 with the following error message:

```
NoMethodError:
       undefined method `values' for [{:plan=>"3-jobs"}]:Array
       Did you mean?  values_at
```

The same code works with version 2.5.4.

**Comment by joshmn** [comment]
I patched this locally. Not sure if it'll break everything else but,

```
module StripeMock
  module RequestHandlers
    module Helpers
      def resolve_subscription_changes(subscription, plans, customer, options = {})
        subscription.merge!(custom_subscription_params(plans, customer, options))
        subscription[:items][:data] = plans.map do |plan|
          if options[:items] && options[:items].size == plans.size
            quantity = options[:items].detect { |item| item[:plan] == plan[:id] }[:quantity] || 1
            Data.mock_subscription_item({ plan: plan, quantity: quantity })
          else
            Data.mock_subscription_item({ plan: plan })
          end
        end
        subscription
      end
   end
end
```

**Comment by timokleemann** [comment]
I ran into the **exact** same issue as @cap10morgan. Reverting to version 2.5.4 fixed it for me.

**Comment by Gunbit** [comment]
i get an error 'no implicit conversion of Symbol into Integer' ( stripe_mock/request_handlers/helpers/subscription_helpers.rb:15 )
if i remove this in subscription_helpers.rb 
`quantity = options[:items] &&
              options[:items].detect { |item| item[:plan] == plan[:id] }[:quantity] || 1
`
it's fine 
`
      stripe_plan = @stripe_test_helper.create_plan(amount: 1190)

      customer = Stripe::Customer.create({
        email: @user.email,
        source: @stripe_test_helper.generate_card_token
      })
      stripeSub = Stripe::Subscription.create customer: customer.id, items: [{ plan: stripe_plan.id }]
`

any ideas?

**Comment by alexmamonchik** [comment]
@Gunbit @timokleemann use github repository instead of gem version

**Comment by aliahmed922** [comment]
I am running into this issue but output is not exactly same, I am getting `TypeError (no implicit conversion of Symbol into Integer)` instead. Any luck? Maybe resolves mine as well.

Code that I am running:
```ruby
Stripe::Subscription.create(customer: customer.id, items: [{ plan: 'my_plan'}])
``` 

Also, when I just use `Stripe::Subscription.create(customer: customer.id, plan: 'my_plan')` (without items . multiple plans), then it's working.

**Comment by ikneg** [comment]
I also updated stripe-mock-ruby from 2.5.4 to 2.5.6 and the test failed with errors. It will succeed if 1 is rewritten as 2. Is this a bug? Or is there a problem with the parameter I'm giving to `Stripe :: Subscription.create`?

1. `quantity = options[:items] && options[:items].detect { |item| item[:plan] == plan[:id] }[:quantity] || 1 `
2. `quantity = options[:items] && options[:items].detect { |item| item[:plan][:id] == plan[:id] }[:quantity] || 1 `

![image](https://user-images.githubusercontent.com/4430244/57828375-45476100-77e6-11e9-9cd6-8d406a11ca9d.png)
