### ISSUE TITLE
v2.2.0 Breaks all my controller specs where .generate_card_token is used twice

### ISSUE THREAD

**Issue by reconstructions** [rebelidealist/stripe-ruby-mock#263]
Thanks to everyone for all the hard work on the 2.2.0 version!  It does break some of my controller tests, any specs which use StripeMock stuff calling `.generate_card_token` more than once break with the following error:

```ruby
Failure/Error: card_two.process! # AASM state machine event
      NoMethodError:
        undefined method `create' for #<Stripe::StripeObject:0x871457e4> JSON: {
          "data": null
        }
```

This only happens if I am making sources twice in a spec, for example when mocking a couple cards for an #index controller action.  If I make only one, there are no errors, for example in the following example the errors go away if I delete one of the cards.  All other tests in the specs pass (typical controller CRUD tests).  Here is the code for the thinest controller test that I can repeat this with:

```ruby
require 'rails_helper'
require 'stripe_mock'
require 'sidekiq/testing'

describe CardsController, :type => :controller do
  
  before(:each) do
    StripeMock.start
  end

  subject(:logged_in_user){ sign_in_user(create(:user), no_capybara: true)}

  subject(:card_one) do
    visa_token = StripeMock.generate_card_token(
      last4: "4242",
      brand: "Visa",
      exp_year: 2019, 
      exp_month: 3 )
    card_one = Card.initialize_stripe_card(logged_in_user, visa_token)
    card_one.save!
    card_one.process! # AASM state machine event
    card_one
  end
  
  subject(:card_two) do
    mastercard_token = StripeMock.generate_card_token(
      last4: "4444",
      brand: "Mastercard",
      exp_year: 2019, 
      exp_month: 3 )
    card_two = Card.initialize_stripe_card(logged_in_user, mastercard_token)
    card_two.save!
    card_two.process! # AASM state machine event
    card_two
  end

  after(:each) do
    StripeMock.stop
    Warden.test_reset!
  end
  
  subject(:logged_in_user_cards){ [card_one, card_two] }
  before{ logged_in_user_cards }
  
  describe "GET#index" do
    
    before(:each) do
      get :index
    end
    
    it "assigns @cards with the User's Cards," do
      expect(assigns(:cards)).to eq(logged_in_user_cards)
    end
  
    it "renders the index template," do
      expect(response).to render_template :index
    end
  end
end
```
 I am using AASM state machines and Sidekiq to process my Stripe transactions, and it is not easy to initialize Cards properly in my tests, which is why I am doing it the way I do.  If someone can suggest a cleaner way (or even better, one that isn't broken) I would be interested to hear about it.  Thanks in advance.  Seems like there are some holes in test coverage which aren't catching changes that are breaking for controller specs.  Either that or my usage needs improving!

**Comment by PlugIN73** [comment]
:+1:

**Comment by louim** [comment]
@reconstructions have you tried with this PR? https://github.com/rebelidealist/stripe-ruby-mock/pull/266 Not sure if it will fix your particular problem, but I encountered similar problem to yours and it fixed mine. Let me know if it helps.

**Comment by reconstructions** [comment]
@louim, thanks for the pointer.  Curious if PR #266 might also fix Issue #253.

**Comment by reconstructions** [comment]
@louim, I tried the 2.2.0 master today, looks like you merged your PR #266 4 days ago, but I get the same error.  Sorry, and thanks for the contribution.  Here is my stack trace:

```ruby
      # /Users/reconstructions/.rvm/gems/ruby-2.1.0/gems/stripe-1.27.2/lib/stripe/stripe_object.rb:241:in `method_missing'
      # ./app/models/card.rb:187:in `set_stripe_card'
      # ./app/models/card.rb:87:in `create_stripe_card'
      # /Users/reconstructions/.rvm/gems/ruby-2.1.0/gems/aasm-4.3.0/lib/aasm/core/event.rb:132:in `invoke_callbacks'
      # /Users/reconstructions/.rvm/gems/ruby-2.1.0/gems/aasm-4.3.0/lib/aasm/core/event.rb:49:in `fire_callbacks'
      # /Users/reconstructions/.rvm/gems/ruby-2.1.0/gems/aasm-4.3.0/lib/aasm/aasm.rb:132:in `aasm_fired'
      # /Users/reconstructions/.rvm/gems/ruby-2.1.0/gems/aasm-4.3.0/lib/aasm/aasm.rb:92:in `aasm_fire_event'
      # /Users/reconstructions/.rvm/gems/ruby-2.1.0/gems/aasm-4.3.0/lib/aasm/persistence/active_record_persistence.rb:148:in `block in aasm_fire_event'
      # /Users/reconstructions/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
      # /Users/reconstructions/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
      # /Users/reconstructions/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
      # /Users/reconstructions/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
      # /Users/reconstructions/.rvm/gems/ruby-2.1.0/gems/aasm-4.3.0/lib/aasm/persistence/active_record_persistence.rb:148:in `aasm_fire_event'
      # /Users/reconstructions/.rvm/gems/ruby-2.1.0/gems/aasm-4.3.0/lib/aasm/base.rb:102:in `process!'
      # ./spec/models/card_spec.rb:47:in `block (2 levels) in <top (required)>'
      # ./spec/models/card_spec.rb:279:in `block (3 levels) in <top (required)>'
      # ./spec/rails_helper.rb:197:in `block (2 levels) in <top (required)>'
```

On line 87 of `card.rb` I called:

```ruby
stripe_card = stripe_customer.sources.create(source: stripe_token_id)
```

**Comment by louim** [comment]
@reconstructions Would you mind sharing what you are doing in `./app/models/card.rb:187:in set_stripe_card'`?

**Comment by reconstructions** [comment]
Not at all, thanks for looking at this.  Here is the stripe bit, the rest is AR stuff:

I am making/retrieving the Stripe customer from `stripe_customer_object` and using it to create a source:
```ruby
stripe_customer = Card.stripe_customer_object(self.user)
stripe_card = stripe_customer.sources.create(source: stripe_token_id)
```

Here is the function I use to make a customer object the first time and retrieve it
after that:
```ruby
def self.stripe_customer_object(user)

      unless user.customer_id?
        customer_object = Stripe::Customer.create(email: user.email )
        user.customer_id = customer_object.id
        user.save
      else
        customer_object = Stripe::Customer.retrieve(user.customer_id)
      end
      customer_object
  end
```

So perhaps this is a problem with the hash for the customer object.

**Comment by reconstructions** [comment]
Any one else manage to reproduce this one?  StripeMock is my only gem which is outdated, I wouldn't want to get left behind...

**Comment by alexmamonchik** [comment]
in 2.2.0 used Stripe 1.28.1 - try to update your gem - I see 1.27.2 in your log.
Also do you save customer after creating a card?
```ruby
stripe_customer = Card.stripe_customer_object(self.user)
stripe_card = stripe_customer.sources.create(source: stripe_token_id)
stripe_customer.save
```

I can't reproduce your error. It works for me.

**Comment by reconstructions** [comment]
Thanks for the input, @alexmamonchik.  Yep, I save my customer after creating a Card:

```
stripe_customer = Card.stripe_customer_object(user)
      stripe_customer.default_source = self.stripe_card_id
      stripe_customer.save
```

Because I am only having these problems in controller specs (my model specs are fine), I suspect that that could be a factor.  So if other people aren't able to repeat this, but only in their model specs, that doesn't mean it couldn't be a bug for those who use controller specs.  It is also possible it has something to do with how I am using state machine calls (AASM) in mocking my cards.

I will try again using Stripe 1.28.1.  I first rolled forward to 2.2.0 the day it was released, and 1.27.2 was the latest Stripe release at that time.  

Hope I don't get left behind for much longer by this release.  I just had to tear Compass Rails out of my app after they abandoned their gem and left me locked at sprockets 2 for more than a year.

**Comment by reconstructions** [comment]
Same result with stripe 1.30.2 and stripe-ruby-mock 2.2.0.  I have 25 test failures.  Most of them are something along this line:

```
Failure/Error: customer.subscriptions.create(
      NoMethodError:
        undefined method `create' for #<Stripe::StripeObject:0x3fc73a54f588> JSON: {
          "data": null
        }
      # /Users/reconstructions/.rvm/gems/ruby-2.1.7@sfrc/gems/stripe-1.30.2/lib/stripe/stripe_object.rb:288:in `method_missing'
      # ./spec/controllers/subscriptions_controller_spec.rb:52:in `block (2 levels) in <top (required)>'
      # ./spec/controllers/subscriptions_controller_spec.rb:192:in `block (3 levels) in <top (required)>'
      # ./spec/rails_helper.rb:197:in `block (2 levels) in <top (required)>'
```
Or things downstream from these failures.

Here's what I am doing on line 52 of my `subscriptions_controller_spec.rb`:

```ruby
customer = Stripe::Customer.retrieve(user.customer_id)
customer.subscriptions.create( plan: stripe_plans.first.id, card: card)
```

This works fine with Stripe 1.30.2 in my app, it is only the tests that fail... Thanks in advance.

**Comment by berpj** [comment]
@reconstructions Same problem here. :+1: Did you find a solution?

**Comment by alexmamonchik** [comment]
if you both have the same problem it is a bug. Please, provide more information - I can't reproduce it. For example version of Stripe API or something else.

**Comment by berpj** [comment]
I'm using stripe `1.30.2`, Stripe API `2015-02-18` and stripe-ruby-mock `2.2.0`.

**Comment by alexmamonchik** [comment]
@berpj thanks. Do you use the same code example?

**Comment by berpj** [comment]
Thanks for looking into the problem. Yes it's the same. I'm now using stripe `1.20.1` and stripe-ruby-mock `2.1.1` and it works: all tests pass.

**Comment by alexmamonchik** [comment]
@reconstructions Can you get last code of gem and check your test again? Updated to stripe 1.31.0

**Comment by reconstructions** [comment]
It's still broken, here are some typical stack traces.  In a couple days I might have some time to try and put together a minimum app which demonstrates this bug.

```
33) SubscriptionsController GET#show renders the show template
      Failure/Error: customer.subscriptions.create(
      NoMethodError:
        undefined method `create' for #<Stripe::StripeObject:0x3ffa662d34a8> JSON: {
        }
      # /Users/reconstructions/.rvm/gems/ruby-2.1.7@sfrc/gems/stripe-1.31.0/lib/stripe/stripe_object.rb:281:in `method_missing'
      # ./spec/controllers/subscriptions_controller_spec.rb:52:in `block (2 levels) in <top (required)>'
      # ./spec/controllers/subscriptions_controller_spec.rb:73:in `block (3 levels) in <top (required)>'
      # ./spec/rails_helper.rb:197:in `block (2 levels) in <top (required)>'
```

All the errors come down to `stripe_object.rb:281:in `method_missing'`.  I didn't do any additional looking into this, but I will try to put together a demo app at some point if I can finish the other stuff I am working on.

Thanks for working on this!

**Comment by reconstructions** [comment]
Whoops, clicked close by accident, sorry.

**Comment by alexmamonchik** [comment]
@reconstructions can you check your test with new version of gem `2.2.1` ?

**Comment by reconstructions** [comment]
That fixed it, great job!
