### ISSUE TITLE
Gem dependencies issue

### ISSUE THREAD

**Issue by amanpoplify** [rebelidealist/stripe-ruby-mock#462]
This gem is not working with stripe 3.0.1 and it always shows 'undefined method `request' for class #<Class:Stripe>' and also in the documentation it defined to  install a version > 2.5.0  but on rubygems this latest version shown in 2.4.1

**Comment by tomgatzgates** [comment]
Looks to have been removed here: https://github.com/stripe/stripe-ruby/commit/de08a9b986404543abd0d78af41035f68ae68163#diff-7bd095922baff1048f819a71f5df2e2cL140

**Comment by dansteele** [comment]
@amanpoplify did you find a workaround for this?
